# This docker compose file is obsolete. The db is now hosted on AWS using Aurora RDS.

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dentistaidadmin
      - POSTGRES_PASSWORD=dentistaidadmin
      - POSTGRES_DB=dentistaiddb
    volumes:
      - dentistaiddb_data:/var/lib/postgresql/data

volumes:
  dentistaiddb_data: